### ISSUE TITLE
Ajouter FusionDirectory dans les outils de gestion des identités

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [sfermigier/guide-oss#5]
Bonjour,

Fusiondirectory n'est pas référencé dans les outils de gestion des identités. Il est fortement utilisé dans les universités, centre de recherche et arrive maintenant dans le secteur public.

je pense qu'il a donc sa place dans ce guide

Cordialement

**Comment by sfermigier** [comment]
Certainement.

**Comment by bilbo-the-hobbit** [comment]
Bonjour,

voilà la PR est faite

Cordialement
